### ISSUE TITLE
Spawn water

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#117]
**Feature overview**
Name: spawn water
TL;DR: our spawn area should have at least 2 tiles of water on each side.

**Details**
A detailed description of what the new feature is.
Ideally make it so it may not be filled with landfill

**Possible methods**
Any ideas you have had about how to implement the feature or any problems that may arise. use the current system where we put concrete and just change tile type to water for two tiles on each side along the wall.

**Additional context**
Not really any additional context.

**Comment by PHIDIAS0303** [comment]
A 3 x 3 tile will work for putting 1 pump unless you want the water pure decoration, otherwise, it should be like this size.
And 4 x 4 title water needs to remove some walls, but it looks better.

Or say just put an offshore pump there directly?
As you can make it a water well pump instead.

![20201127182223_1](https://user-images.githubusercontent.com/10016767/100432876-90ca1300-30dd-11eb-81df-8c801690c3b0.jpg)
![20201127181519_1](https://user-images.githubusercontent.com/10016767/100432494-07b2dc00-30dd-11eb-8288-1ba1e0fbf490.jpg)

**Comment by Cooldude2606** [comment]
Feature has been implemented in #208 and merged into dev branch. Closing issue.
