### ISSUE TITLE
Warp error message

### ISSUE THREAD

**Issue by kevintayloruk** [explosivegaming/scenario#166]
**Factorio version**
Version number: 0.18.31

**Scenario version**
Version number: Whatever's running on S1 15th June 2020

**Bug description**
After warping the Warp message when you try to create a Warp too close to an existing one gives the warp you travelled from rather than the warp you are too close to.  This is resolved by walking "far enough" away to create a warp then back.

**Reproduction method**
1. From warp 'B' warp to warp 'A'
2. Hover over '+' on warp list to create new warp
3. Look at mouseover text.

**Expected behavior**
Mouseover text would show warp 'A' too close

**Screenshots**
<img width="1552" alt="Screenshot 2020-06-14 at 14 22 56" src="https://user-images.githubusercontent.com/2964154/84670407-01a9b400-af1e-11ea-929c-85d74715ba76.png">

**Additional context**
None

**Comment by Cooldude2606** [comment]
This issue is a result of overly aggressive lag reduction used to avoid api calls.
The [code](https://github.com/explosivegaming/scenario/blob/e27502c4a48914929ae2481d0d965c925f9c4f96/modules/gui/warp-list.lua#L620) that is used for this will only update the tooltip when you were able to make a warp but now are unable to, seen on line 599.
Either we remove this check, resulting in alot of api calls, or we need a way to check if the closest warp has changed.

**Comment by Cooldude2606** [comment]
Fixed in [v6.0.10](https://github.com/explosivegaming/scenario/releases/tag/6.0.10)
See [commit](https://github.com/explosivegaming/scenario/commit/f1520e77e77e9d3ce83bbedf540d3fe444189d52)
