### ISSUE TITLE
Reports module (clear) replies with 'command complete' even when not

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#194]
**Factorio version**
Version number: 1

**Scenario version**
Version number: current 6.1.1

**Bug description**
When clearing reports from [modules.control.reports").remove_all] it reports command complete even when the wrong name or typo happens

**Reproduction method**
1. clear a name that does not exist
2. get told command complete with no error from the server

**Expected behavior**
would like an error returned (like what jail does)

**Comment by Cooldude2606** [comment]
Could you provide the command which you are using, because the control modules for jail and report do the same thing for an invalid player. And the commands /clear-reports and /unjail return errors for invalid players because of the argument parse.
![output](https://i.imgur.com/gLWWrf1.png)

**Comment by Cooldude2606** [comment]
As discusted on discord the command which was being is:
```lua
/interface require("modules.control.reports").remove_all("${toClear}", "${msg.member.displayName}")
```

As all modules, outside of core and util, do not raise errors for invalid arguments I do not consider this a bug.
Further more, the interface command is designed as a techical interface with the lua scenario with safe guards against desyncs and errors. As such, you should use the command to return a value of success rather than raise an error.
An example of how you can return a success value:
```lua
/interface return require("modules.control.reports").remove_all("${toClear}", "${msg.member.displayName}") == true
```
